### ISSUE TITLE
They Love Crypto. They’re Trying to Buy the Constitution.

### ISSUE THREAD

**Issue by GrahamSH-LLK** [GrahamSH-LLK/current-events#1]
### Source

New York Times

### Title

They Love Crypto. They’re Trying to Buy the Constitution.

### Author

Kevin Roose

### Link

https://www.nytimes.com/2021/11/17/business/crypto-constitution-sothebys.html

### Write a 6-8 sentence summary that includes the main idea of the article

A large group of people known as ConstitutionDAO has joined together to buy a copy of the Constitution at auction. To amass enough money to buy it, they are pooling cryptocurrency in something called a DAO. As of Wednesday, $12.8 million has been raised. A DAO, also known as a decentralized autonomous organization, is basically a shared bank account. In the past, experiments like this have been derailed, so it is up in the air as to what will happen. The copy being auctioned is the only known privately owned copy of the Constitution. However, the group plans to team up with a prominent museum so that anyone can see it. According to Alice Ma, one of the organizers, “We’re going to stop it from going into more private hands and actually open-source it, make it a public good."

### Who was this article written for? Why do you think this?

This article was written for anybody living in the US or interested in Cryptocurrency. The constitution is one of our founding documents, and we don't want it falling into the wrong hands. People interested in Cryptocurrency will want to know about this new group and whether it succeeds.

### What was this article trying to accomplish?

This article was trying to inform people about the group's plan to buy this copy of the Constitution. It showed how it might work, but there's also a good chance it doesn't. It shed light on the internals of the group.

### What is your reaction to this article? What is your opinion of this situation after reading the article?

My reaction to this article was part hopeful and part scared. Their mission sounds good, but I'm not sure how well they can execute it. They don't sound very well organized. My opinion is that they should really make sure that they leave all of the handlings up to people who know what they're doing.

### Take some notes and come up with talking points for when you need to share

- A large group of people known as ConstitutionDAO has joined together to buy a copy of the Constitution
- They have so far raised $12.8 million
- They are crowdfunding the money using Ethereum, a cryptocurrency
- This is the only known privately owned copy of the Constitution
- It is up for auction at Sotheby's

### Notes from _______________
- 
-
- 
- 
- 
- 
### Notes from _______________
- 
-
- 
- 
- 
-

**Comment by ninjamar** [comment]
cool

**Comment by GrahamSH-LLK** [comment]
> cool

oh I should private this. I'm doing school work via github issue forms.... and it works really well 😄

**Comment by ninjamar** [comment]
oh lol

**Comment by Quantum-Codes** [comment]
Wow! If this is a homework,  then you will get 10/10 lol

**Comment by ninjamar** [comment]
> Wow! If this is a homework, then you will get 10/10 lol

agreed
